### ISSUE TITLE
SubAccount can see what Admin account can see only via cookie modification

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#23]
IT is not really security issue as you cannot perform any action but I believe this would help hackers to have better overview of the system if they will see admin account possibilities and endpoint called.

1. Log in as a subaccount account (no admin right) -> cookie has key **role** set **0**
2, In Chrome developer mode go to the console and type in : **document.cookie="role=1"**
3, Refresh the page and you will see what admin user can see

**Comment by plalx** [comment]
I dont think this is a problem, as long as the backend honors the appropriate role and not the client-side one obviously. Client state will always be mutable, whether in `sessionStorage`, cookies or JavaScript state and since it's a Vue application it makes sense that the role is stored client-side. 

You could argue that the server should only serve sources specific to the user's role, but that would certainly add some UI code complexity.
