### ISSUE TITLE
Visualize what is happening and endorsment explaining

### ISSUE THREAD

**Issue by Angus23203** [disy-yin/CrossChain#36]
Not a technical issue but is there a way to visualize what is actually happening on the childchains when an endorsement is running. 

Some questions that pop in my mind meanwhile:

- What happens on the childchains itself, can we see the transactions on the childchain(s) somehow? Something like address x on childchain x  makes transaction y to address z on childchain z or isn't this how it should work?

- What does an endorsementcontract do and why is it needed? Why does it create a transaction on almost every block on the mainchain when its running. I assume its running the addEndorsement function. 

- Why does the 'Reward' column say 0.3 wtc but the reward per transaction is 0.1 wtc. If this is 0.3 wtc devided by the number of SMNs maybe visualize this?

- Why does an SMN need worker addresses.

**Comment by slklubaoding** [comment]
1. Endorsement means uploading child chain data to the parent chain. Child chains cannot perform any changes. Block endorsement is obtaining hash for each child chain block. Business endorsement refers to a child chain business contract. Business contract is used to store specific business data on child chains. During endorsement, business data are obtained from a business contract.
2. Endorsement contract is used to process child chain data and upload it to the parent chain. addEndorsement function serves to upload processed data to the parent chain, therefore parent chain has frequent upload transactions.
3. "Reward" means profit from endorsing a data string. "SMN Count" stands for the number of SMNs which completed the endorsement. Therefore per-SMN reward shall be Reward/SMN Count.
4. Workers are introduced to ensure SMN account safety: each endorsement transaction requires account private key for signature. Since SMN accounts have a lot of tokens, they are not suitable for transaction signing.

**Comment by Angus23203** [comment]
Thanks! this makes a lot of sense already.
Do you have the addresses of the SubchainManageContract and the PermissionManageContract so we can have a look at it?

Also what is the function of the TemplateManageContract?

**Comment by ko12ko** [comment]
@Angus23203

**Comment by ko12ko** [comment]
TemplateManageContract is a template management contract used to deploy endorsement contracts in the management system.
The three contracts you mentioned are all used in the management system. At present, we are adding and optimizing the management system functions.
@Angus23203

**Comment by Angus23203** [comment]
@ko12ko thanks. 
Are we going to test the management system? 
For instance will we be able to create a childchain, connect it to the mainchain so it shows up in de smn crosschain front end and create endorsements for it?

**Comment by ko12ko** [comment]
@Angus23203 
Please wait for official Announcement. Thank you.
